name: trackernity_watcher
version: 1.0.0+1
publish_to: none
description: An app for monitoring/watching tracked activity by TrackernityApp
environment: 
  sdk: '>=2.15.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.4
  get_cli: ^1.7.1
  get: 4.6.1
  google_maps_flutter: 2.1.1
  http: 0.13.4
  google_maps_flutter_web: 0.3.2+1
  intl: 0.17.0
  sliding_up_panel: 2.0.0+1
  socket_io_client: 1.0.2
  uuid: ^3.0.5
  fluttertoast: 8.0.8
  shared_preferences: 2.0.13
  custom_info_window: 1.0.1
  flutter: 
    sdk: flutter
  clippy_flutter: ^2.0.0-nullsafety.1
  encrypt: ^5.0.1

dev_dependencies: 
  flutter_lints: ^1.0.4
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
  fonts: 
    - family: Consolas
      fonts: 
        - asset: assets/fonts/Consolas.ttf
    - family: Dongle
      fonts: 
        - asset: assets/fonts/dongle_bold.ttf
  uses-material-design: true

